"""First migration for current db schema

Revision ID: 4af1e1ffdd2b
Revises: 
Create Date: 2025-05-09 13:03:14.080980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af1e1ffdd2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('catid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('catid')
    )
    op.create_table('group_roles',
    sa.Column('roleid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('roleid')
    )
    op.create_table('group_types',
    sa.Column('grtype', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('grtype')
    )
    op.create_table('notes',
    sa.Column('noteid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('noteid')
    )
    op.create_table('users',
    sa.Column('usid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=False),
    sa.Column('lname', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('usid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('groups',
    sa.Column('grid', sa.Integer(), nullable=False),
    sa.Column('grname', sa.String(length=50), nullable=False),
    sa.Column('grtype', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grtype'], ['group_types.grtype'], ),
    sa.PrimaryKeyConstraint('grid')
    )
    op.create_table('group_memberships',
    sa.Column('usid', sa.Integer(), nullable=False),
    sa.Column('grid', sa.Integer(), nullable=False),
    sa.Column('roleid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grid'], ['groups.grid'], ),
    sa.ForeignKeyConstraint(['roleid'], ['group_roles.roleid'], ),
    sa.ForeignKeyConstraint(['usid'], ['users.usid'], ),
    sa.PrimaryKeyConstraint('usid', 'grid')
    )
    op.create_table('past_group_balances',
    sa.Column('balanceid', sa.Integer(), nullable=False),
    sa.Column('grid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('up_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grid'], ['groups.grid'], ),
    sa.PrimaryKeyConstraint('balanceid')
    )
    op.create_table('transactions',
    sa.Column('trid', sa.Integer(), nullable=False),
    sa.Column('usid', sa.Integer(), nullable=False),
    sa.Column('grid', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('income', sa.Boolean(), nullable=False),
    sa.Column('catId', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('noteid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catId'], ['categories.catid'], ),
    sa.ForeignKeyConstraint(['grid'], ['groups.grid'], ),
    sa.ForeignKeyConstraint(['noteid'], ['notes.noteid'], ),
    sa.ForeignKeyConstraint(['usid'], ['users.usid'], ),
    sa.PrimaryKeyConstraint('trid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('past_group_balances')
    op.drop_table('group_memberships')
    op.drop_table('groups')
    op.drop_table('users')
    op.drop_table('notes')
    op.drop_table('group_types')
    op.drop_table('group_roles')
    op.drop_table('categories')
    # ### end Alembic commands ###
